[project]
name = "ml-router"
version = "0.1.0"
description = "A distributed ML inference router"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiocache>=0.12.3",
    "alembic>=1.18.1",
    "asyncpg>=0.31.0",
    "docker>=7.1.0",
    "fastapi[standard]>=0.128.0",
    "gunicorn>=24.1.1",
    "msgspec>=0.20.0",
    "omegaconf>=2.3.0",
    "passlib>=1.7.4",
    "pendulum>=3.1.0",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "pydantic-settings>=2.12.0",
    "python-jose>=3.5.0",
    "python-json-logger>=4.0.0",
    "redis>=7.1.0",
    "sqlalchemy>=2.0.46",
    "tenacity>=9.1.2",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "locust>=2.43.1",
    "prek>=0.2.29",
    "pyrefly>=0.49.0",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.13",
]

# Pytest configuration
[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"


# Pyrefly header
[tool.pyrefly]

#### configuring what to type check and where to import from
project-includes = ["src", "."]
project-excludes = ["**/.[!/.]*"]
search-path = ["."]
