"""[chore] Added updated_at field

Revision ID: 7978bc2d3910
Revises: a76e6b62ebbc
Create Date: 2026-01-29 18:33:37.543551

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7978bc2d3910"
down_revision: Union[str, Sequence[str], None] = "a76e6b62ebbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column(
        "api_keys", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )

    # Update existing rows with current timestamp
    op.execute(
        "UPDATE api_keys SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL"
    )

    # Now make the column NOT NULL
    op.alter_column("api_keys", "updated_at", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "updated_at")
    # ### end Alembic commands ###
