"""[chore] Reverted back to strings instead of using DB enums

Revision ID: a76e6b62ebbc
Revises:
Create Date: 2026-01-29 01:42:38.773733

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a76e6b62ebbc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
